CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    MANUFACTURER_NAME VARCHAR(100),
    PRODUCT_REFERENCE_NUMBER VARCHAR(64) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(500),
    PRICE_IN_DOLLARS NUMERIC,
    PRODUCT_LENGTH VARCHAR(20),
    PRODUCT_HEIGHT VARCHAR(20),
    PRODUCT_WIDTH VARCHAR(20),
    PRODUCT_STYLE VARCHAR(64), 
    PRODUCT_COLOR VARCHAR(64), 
    PRODUCT_URL VARCHAR(255)
);