CREATE TABLE USER_PERSONALITY (
    ID VARCHAR(100) NOT NULL, 
    PERSONALITY_TYPES VARCHAR(4) NOT NULL, 
    PERSONALITY_STRENGTH INT NOT NULL,
    CONSTRAINT FK_USERDATA
        FOREIGN KEY(ID)
        REFERENCES USER_DATA(ID),
    CONSTRAINT FK_PERSONALITY
        FOREIGN KEY(PERSONALITY_TYPES)
        REFERENCES PERSONALITY(personality_types)
);