CREATE TABLE PRODUCT_IMAGE (
    PRODUCT_ID VARCHAR(100) NOT NULL,   
    PRODUCT_IMAGE VARCHAR(500) NOT NULL,
    CONSTRAINT FK_PRODUCT
        FOREIGN KEY(PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);